.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Nils Naumann <nau@gmx.net>,
.\" (C) Copyright 2018 Matthias Kraft <m.kraft@gmx.com>,
.\"
.TH FRITZIDENT  "February 12th, 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
fritzident \- parental control for Fritz!Box
.SH SYNOPSIS
.B fritzident
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B fritzident
daemon.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics,
.\" respectively.
\fBfritzident\fP is a program that is amending the parental control function of
the AVM Fritz!Box.  It mimics the standard AVM Windows application that allows
the Fritz!Box to recognize individual users connecting to the Internet.
.br
This application is supposed to run under control of inetd or systemd.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long options
starting with two dashes (-).  A summary of options follows:
.TP
.B \-h, \-\-help
display a short help and exit.
.TP
.B \-v, \-\-verbose
increase the logging level.  Per default only errors and warnings are logged via
the syslog.  This option might be given up to three times in which case also all
debugging messages are written to the log.
.TP
.B \-d, \-\-domain  domainname
fake a Windows domain to prepend before the reported user name.  There is no
domain prepended per default.
.TP
.B \-p, \-\-port  portnumber
change the port number to use.  Defaults to the expected 14013.
.TP
.B \-i, \-\-umin  min_uid
change the min. user id reported as non-system user.  Defaults to 1000, which is
usually the first real user id on Linux systems.
.TP
.B \-a, \-\-umax  max_uid
change the max. user id reported as non-system user.  Defaults to 65533, which
usually is the last usable user id on Linux systems.
.SH SECURITY
The intent of this service is to disclose information about the internal
configuration of the machine!
.PP
.B So if you do not need this service, do not install and start it!
.PP
But as you are reading this page, you probably see a need to make use of this
service.  Just keep in mind, that once this service is running, the AVM
Fritz!Box is not the only one knowing how to connect to this service.  You may
want to configure a narrow rule into your machine's local firewall to only
allow traffic from your AVM Fritz!Box to the port of this service and vice
versa.
.SH INTERNALS
At startup, fritzident sets up a socket and waits for a connection.  It then
sends out a prompt message and waits for a single command, then sends the
respective response.  The prompt message is "AVM IDENT", and is
required for the Fritz!Box to recognize the service.
.PP
Recognized commands:
.IP USERS
return a list of known users.
.IP "TCP ip:port"
return the name of the user for the specified TCP connection.
.IP "UDP ip:port"
idem, but for an UDP connection.
.PP
The prompt, as well as all replies, are terminated by a CR & NL (ASC 13 + ASC
10).  Commands are recognized with either CR & NL or just NL line termination.
This allows fritzident to be tested interactively.
.SH COPYRIGHT
Copyright \(co 2013 Andre Larbiere <andre@larbiere.eu>
.br
Copyright \(co 2015 Nils Naumann <nau@gmx.net>
.br
Copyright \(co 2018 Matthias Kraft <m.kraft@gmx.com>
.br
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.  There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR inetd(8),  RFC-1413.
.br